# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171121_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextras',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userextras',
            name='house',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='userextras',
            name='postcode',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='userextras',
            name='street',
            field=models.CharField(max_length=50),
        ),
    ]
