# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_custom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom',
            old_name='request',
            new_name='custom_description',
        ),
    ]
